### ISSUE TITLE
Create demo notebooks for jupyterlab-plotly, jupyter-dash and jupyter-matplotlib

### ISSUE THREAD

**Issue by Ito-Matsuda** [StatCan/jupyter-notebooks#30]
Demo notebooks request from [kubeflow-containers 104](https://github.com/StatCan/kubeflow-containers/issues/104) and related to [kubeflow-containers update to jupyter-dash127](https://github.com/StatCan/kubeflow-containers/issues/127)

Could look to base example off of Christian's ipynb [here](https://github.com/StatCan/jupyter-notebooks/blob/master/scikitlearn/01-NumbersRandomForests.ipynb) 

@ca-scribner Any folder in particular you want these notebooks to be in? As a refresher these extensions are found in `minimal-notebook`

**Comment by ca-scribner** [comment]
How about for now we add a `./plotting` folder off the root and put them
there?  I don't see an obvious place for it
