### ISSUE TITLE
Spark/Databricks Example

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/jupyter-notebooks#5]
Would be great to see databricks API integration and ideally pyspark examples.

**Comment by blairdrummond** [comment]
@ca-scribner 

https://github.com/krishnan-r/sparkmonitor

**Comment by ca-scribner** [comment]
Successfully connected to a path 2 databricks cluster using databricks-connect and info about the databricks instance and a live cluster.  Can run pyspark commands from a local pycharm, etc., using cluster for compute.  Not sure how to translate this to using pyspark from a notebook server in kubernetes.  

I don't think the databricks-connect method is the way - is a connection through vanilla pyspark appropriate?  Steve's [medium post](https://medium.com/@szinck/setting-up-pyspark-jupyter-and-minio-on-kubeflow-kubernetes-aab98874794f) goes that route but I couldn't fully reproduce it.  

@sylus / @zachomedia any tips or past code fragments using pyspark?  I only saw [this](https://github.com/StatCan/actions/blob/c10f1a4457d1d46410964028f43c3444dda478ad/kubeflow-databricks/examples/databricks_cluster_pipeline.py) in the repos

**Comment by sylus** [comment]
I still need to do some final tweaks and will let you know but this is roughly how I ported the actions one over and gave an example using kfp dsl.

https://github.com/StatCan/jupyter-notebooks/blob/aa95f12590d5f288aad8be43bee930d19bc002b2/ai-pipeline/03-DataBricksComputePi.ipynb
